### ISSUE TITLE
Build Issues with ESPHome 2022.6.2

### ISSUE THREAD

**Issue by mightea** [jplitza/esphome-obis-sensor#8]
I'm trying to integrate this component with a `esp01_1m` ESP8266 (Hichi IR WiFi) and I'm getting a build error. Are you able to build with the newest ESPHome version?

```
Processing esph-smart-meter (board: esp01_1m; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|-- <ESPAsyncWebServer-esphome> 2.1.0
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <DNSServer> 1.1.1
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|-- <ArduinoJson> 6.18.5
Compiling /data/esph-smart-meter/.pioenvs/esph-smart-meter/src/main.cpp.o
Archiving /data/esph-smart-meter/.pioenvs/esph-smart-meter/libaf0/libHash.a
Compiling /data/esph-smart-meter/.pioenvs/esph-smart-meter/lib67b/ESP8266WiFi/ESP8266WiFi.cpp.o
Compiling /data/esph-smart-meter/.pioenvs/esph-smart-meter/lib67b/ESP8266WiFi/ESP8266WiFiAP.cpp.o
Compiling /data/esph-smart-meter/.pioenvs/esph-smart-meter/lib67b/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o
Compiling /data/esph-smart-meter/.pioenvs/esph-smart-meter/lib67b/ESP8266WiFi/ESP8266WiFiGratuitous.cpp.o
Compiling /data/esph-smart-meter/.pioenvs/esph-smart-meter/lib67b/ESP8266WiFi/ESP8266WiFiMulti.cpp.o
Compiling /data/esph-smart-meter/.pioenvs/esph-smart-meter/lib67b/ESP8266WiFi/ESP8266WiFiSTA-WPS.cpp.o
Compiling /data/esph-smart-meter/.pioenvs/esph-smart-meter/lib67b/ESP8266WiFi/ESP8266WiFiSTA.cpp.o
/config/esphome/smart-meter.yaml: In function 'void setup()':
/config/esphome/smart-meter.yaml:67:56: error: reference to 'optional' is ambiguous
   67 | #       - uart.write:
      |                                                        ^       
In file included from src/esphome/core/component.h:7,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/optional.h:36:28: note: candidates are: 'template<class T> class esphome::optional'
   36 | template<typename T> class optional {  // NOLINT
      |                            ^~~~~~~~
In file included from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/node_handle.h:39,
                 from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/hashtable.h:37,
                 from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/unordered_map:46,
                 from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/functional:61,
                 from src/esphome/core/component.h:4,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/optional:60:11: note:                 'template<class _Tp> class std::optional'
   60 |     class optional;
      |           ^~~~~~~~
/config/esphome/smart-meter.yaml:67:64: error: expected '{' before '<' token
   67 | #       - uart.write:
      |                                                                ^
/config/esphome/smart-meter.yaml:67:65: error: expected primary-expression before 'float'
   67 | #       - uart.write:
      |                                                                 ^    
/config/esphome/./components/common/../sensors/wifi_signal_percentage.yaml:30:50: error: reference to 'optional' is ambiguous
In file included from src/esphome/core/component.h:7,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/optional.h:36:28: note: candidates are: 'template<class T> class esphome::optional'
   36 | template<typename T> class optional {  // NOLINT
      |                            ^~~~~~~~
In file included from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/node_handle.h:39,
                 from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/hashtable.h:37,
                 from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/unordered_map:46,
                 from /data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/functional:61,
                 from src/esphome/core/component.h:4,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/optional:60:11: note:                 'template<class _Tp> class std::optional'
   60 |     class optional;
      |           ^~~~~~~~
/config/esphome/./components/common/../sensors/wifi_signal_percentage.yaml:30:58: error: expected '{' before '<' token
/config/esphome/./components/common/../sensors/wifi_signal_percentage.yaml:30:59: error: expected primary-expression before 'float'
Compiling /data/esph-smart-meter/.pioenvs/esph-smart-meter/lib67b/ESP8266WiFi/ESP8266WiFiScan.cpp.o
Compiling /data/esph-smart-meter/.pioenvs/esph-smart-meter/lib67b/ESP8266WiFi/WiFiClient.cpp.o
*** [/data/esph-smart-meter/.pioenvs/esph-smart-meter/src/main.cpp.o] Error 1
========================= [FAILED] Took 18.65 seconds =========================
```

As soon as I remove the component everything builds fine. Any hints would be appreciated, thank you.

**Comment by jplitza** [comment]
Sorry for the very late response.

Yes, I just built the OBIS component successfully with the latest ESPhome.

Since the log is mentioning "optional", I suspect my syntax for inline comments in the example config is invalid:
https://github.com/jplitza/esphome_components/blob/8d7bde643861b78b86a269862bccca292becb883/example_obis.yml#L16
Can you try to remove the `# optional` at the end of that line? If that doesn't work, please post your full config for further analysis.

**Comment by ckz666** [comment]
Got also problems with ESPHome 2022.10.2 it only happens if i use also a binary sensor and text_sensor template. Without the binary sensor and text_sensor template, everything compiles fine...

`INFO Reading configuration esp-smartmeter-test2.yaml...
INFO Cloning https://github.com/jplitza/esphome_components.git@None
INFO Generating C++ source...
INFO Compiling app...
***************************************************************************************************************
Obsolete PIO Core v6.0.2 is used (previous was 6.1.4)
Please remove multiple PIO Cores from a system:
https://docs.platformio.org/en/latest/core/installation/troubleshooting.html
***************************************************************************************************************
Processing smartmeter (board: d1_mini; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
---------------------------------------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- ESPAsyncTCP-esphome @ 1.2.3
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- ESPAsyncTCP-esphome @ 1.2.3
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- AsyncMqttClient-esphome @ 0.8.6
|   |-- ESPAsyncTCP-esphome @ 1.2.3
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/smartmeter/src/esphome/components/obis/obis.cpp.o
Compiling .pioenvs/smartmeter/src/main.cpp.o
src/main.cpp: In function 'void setup()':
src/main.cpp:482:55: error: reference to 'optional' is ambiguous
  482 |   template__templatetextsensor->set_template([=]() -> optional<std::string> {
      |                                                       ^~~~~~~~
In file included from src/esphome/core/component.h:7,
                 from src/esphome/components/binary_sensor/automation.h:5,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/optional.h:36:28: note: candidates are: 'template<class T> class esphome::optional'
   36 | template<typename T> class optional {  // NOLINT
      |                            ^~~~~~~~
In file included from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/node_handle.h:39,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/hashtable.h:37,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/unordered_map:46,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/functional:61,
                 from src/esphome/core/component.h:4,
                 from src/esphome/components/binary_sensor/automation.h:5,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/optional:60:11: note:                 'template<class _Tp> class std::optional'
   60 |     class optional;
      |           ^~~~~~~~
src/main.cpp:482:63: error: expected '{' before '<' token
  482 |   template__templatetextsensor->set_template([=]() -> optional<std::string> {
      |                                                               ^
src/main.cpp:482:75: error: expected primary-expression before '>' token
  482 |   template__templatetextsensor->set_template([=]() -> optional<std::string> {
      |                                                                           ^
src/main.cpp:482:77: error: expected primary-expression before '{' token
  482 |   template__templatetextsensor->set_template([=]() -> optional<std::string> {
      |                                                                             ^
esp-smartmeter-test2.yaml:89:51: error: reference to 'optional' is ambiguous
In file included from src/esphome/core/component.h:7,
                 from src/esphome/components/binary_sensor/automation.h:5,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/optional.h:36:28: note: candidates are: 'template<class T> class esphome::optional'
   36 | template<typename T> class optional {  // NOLINT
      |                            ^~~~~~~~
In file included from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/node_handle.h:39,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/hashtable.h:37,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/unordered_map:46,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/functional:61,
                 from src/esphome/core/component.h:4,
                 from src/esphome/components/binary_sensor/automation.h:5,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/optional:60:11: note:                 'template<class _Tp> class std::optional'
   60 |     class optional;
      |           ^~~~~~~~
esp-smartmeter-test2.yaml:89:59: error: expected '{' before '<' token
esp-smartmeter-test2.yaml:89:60: error: expected primary-expression before 'float'
esp-smartmeter-test2.yaml:88:53: error: reference to 'optional' is ambiguous
In file included from src/esphome/core/component.h:7,
                 from src/esphome/components/binary_sensor/automation.h:5,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/optional.h:36:28: note: candidates are: 'template<class T> class esphome::optional'
   36 | template<typename T> class optional {  // NOLINT
      |                            ^~~~~~~~
In file included from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/node_handle.h:39,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/hashtable.h:37,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/unordered_map:46,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/functional:61,
                 from src/esphome/core/component.h:4,
                 from src/esphome/components/binary_sensor/automation.h:5,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/optional:60:11: note:                 'template<class _Tp> class std::optional'
   60 |     class optional;
      |           ^~~~~~~~
esp-smartmeter-test2.yaml:88:61: error: expected '{' before '<' token
esp-smartmeter-test2.yaml:88:62: error: expected primary-expression before 'float'
*** [.pioenvs/smartmeter/src/main.cpp.o] Error 1
========================================= [FAILED] Took 4.28 seconds =========================================`

here is my config.yaml

`external_components:
  - source: github://jplitza/esphome_components
#external_components:
  #- source:
  #    type: local
  #    path: my_components
  #    #components: [ obis ]
  #- source: github://oromis911/Logarex-LK13B
  #  components: [ obis ]
substitutions:
  lower_devicename: "wemosd1mini"
  device_name: "smartmeter"
  config_version: "v2022.10.29"

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".climax"

  ap:
    ssid: "{device_name}"
    password: "12345678"

logger:
  baud_rate: 0

ota:
  password: "pass"
  port: 8266
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: ${device_name}
  topic_prefix: ${lower_devicename}/${device_name}
  discovery: false

web_server:
  port: 80
  #local: true

uart:
    id: uart_bus
    rx_pin: GPIO3
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1

obis:
  id: obis0
  uart_id: uart_bus

globals:
  - id: total_pulses
    type: int
    restore_value: false
    initial_value: '706615'  # hier kann der Gaszählerstand initialisiert werden

binary_sensor:
  - platform: gpio
    id: internal_pulse_counter
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
    name: "Live-Impuls"
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - lambda: id(total_pulses) += 1;

sensor:
  - platform: template
    name: "Gasverbrauch"
    device_class: gas
    unit_of_measurement: "m³"
    state_class: "total_increasing"
    accuracy_decimals: 2
    lambda: |-
      return id(total_pulses) * 0.01;
  - platform: template
    name: "Gaswert Raw"
    #update_interval: 2s
    device_class: gas
    unit_of_measurement: ""
    state_class: "total_increasing"
    accuracy_decimals: 0
    lambda: |-
      return id(total_pulses);
  - platform: obis
    obis_id: obis0
    channel: "1-0:1.8.0*255"
    name: "Bezug"
    unit_of_measurement: "kWh"
    accuracy_decimals: 7
#  - platform: obis
#    channel: "1-0:16.7.0*255"
#    name: "Wirkleistung"
#    unit_of_measurement: "W"
#    accuracy_decimals: 2
#  - platform: obis
#    channel: "1-0:2.8.0*255"
#    name: "Einspeisung"
#    unit_of_measurement: "kWh"
#    accuracy_decimals: 7
#  - platform: obis
#    channel: "1-0:14.7.0*255"
#    name: "Frequenz"
#    unit_of_measurement: "Hz"
#    accuracy_decimals: 2
#  - platform: obis
#    channel: "1-0:32.7.0*255"
#    name: "U-L1"
#    unit_of_measurement: "V"
#    accuracy_decimals: 2
#  - platform: obis
#    channel: "1-0:52.7.0*255"
#    name: "U-L2"
#    unit_of_measurement: "V"
#    accuracy_decimals: 2
#  - platform: obis
#    channel: "1-0:72.7.0*255"
#    name: "U-L3"
#    unit_of_measurement: "V"
#    accuracy_decimals: 2
#  - platform: obis
#    channel: "1-0:31.7.0*255"
#    name: "I-L1"
#    unit_of_measurement: "A"
#    accuracy_decimals: 2
#  - platform: obis
#    channel: "1-0:51.7.0*255"
#    name: "I-L2"
#    unit_of_measurement: "A"
#    accuracy_decimals: 2
#  - platform: obis
#    channel: "1-0:71.7.0*255"
#    name: "I-L3"
#    unit_of_measurement: "A"
#    accuracy_decimals: 2

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
  - platform: template
    name: "Config Version"
    lambda: |-
      return {"$config_version"};

switch:
  - platform: restart
    name: "Restart"
`

**Comment by ckz666** [comment]
Got also problems with ESPHome 2022.10.2 it only happens if i use also a binary sensor and text_sensor template. Without the binary sensor and text_sensor template, everything compiles fine...

```
INFO Reading configuration esp-smartmeter-test2.yaml...
INFO Cloning https://github.com/jplitza/esphome_components.git@None
INFO Generating C++ source...
INFO Compiling app...
***************************************************************************************************************
Obsolete PIO Core v6.0.2 is used (previous was 6.1.4)
Please remove multiple PIO Cores from a system:
https://docs.platformio.org/en/latest/core/installation/troubleshooting.html
***************************************************************************************************************
Processing smartmeter (board: d1_mini; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
---------------------------------------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- ESPAsyncTCP-esphome @ 1.2.3
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- ESPAsyncTCP-esphome @ 1.2.3
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- AsyncMqttClient-esphome @ 0.8.6
|   |-- ESPAsyncTCP-esphome @ 1.2.3
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/smartmeter/src/esphome/components/obis/obis.cpp.o
Compiling .pioenvs/smartmeter/src/main.cpp.o
src/main.cpp: In function 'void setup()':
src/main.cpp:482:55: error: reference to 'optional' is ambiguous
  482 |   template__templatetextsensor->set_template([=]() -> optional<std::string> {
      |                                                       ^~~~~~~~
In file included from src/esphome/core/component.h:7,
                 from src/esphome/components/binary_sensor/automation.h:5,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/optional.h:36:28: note: candidates are: 'template<class T> class esphome::optional'
   36 | template<typename T> class optional {  // NOLINT
      |                            ^~~~~~~~
In file included from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/node_handle.h:39,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/hashtable.h:37,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/unordered_map:46,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/functional:61,
                 from src/esphome/core/component.h:4,
                 from src/esphome/components/binary_sensor/automation.h:5,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/optional:60:11: note:                 'template<class _Tp> class std::optional'
   60 |     class optional;
      |           ^~~~~~~~
src/main.cpp:482:63: error: expected '{' before '<' token
  482 |   template__templatetextsensor->set_template([=]() -> optional<std::string> {
      |                                                               ^
src/main.cpp:482:75: error: expected primary-expression before '>' token
  482 |   template__templatetextsensor->set_template([=]() -> optional<std::string> {
      |                                                                           ^
src/main.cpp:482:77: error: expected primary-expression before '{' token
  482 |   template__templatetextsensor->set_template([=]() -> optional<std::string> {
      |                                                                             ^
esp-smartmeter-test2.yaml:89:51: error: reference to 'optional' is ambiguous
In file included from src/esphome/core/component.h:7,
                 from src/esphome/components/binary_sensor/automation.h:5,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/optional.h:36:28: note: candidates are: 'template<class T> class esphome::optional'
   36 | template<typename T> class optional {  // NOLINT
      |                            ^~~~~~~~
In file included from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/node_handle.h:39,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/hashtable.h:37,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/unordered_map:46,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/functional:61,
                 from src/esphome/core/component.h:4,
                 from src/esphome/components/binary_sensor/automation.h:5,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/optional:60:11: note:                 'template<class _Tp> class std::optional'
   60 |     class optional;
      |           ^~~~~~~~
esp-smartmeter-test2.yaml:89:59: error: expected '{' before '<' token
esp-smartmeter-test2.yaml:89:60: error: expected primary-expression before 'float'
esp-smartmeter-test2.yaml:88:53: error: reference to 'optional' is ambiguous
In file included from src/esphome/core/component.h:7,
                 from src/esphome/components/binary_sensor/automation.h:5,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/optional.h:36:28: note: candidates are: 'template<class T> class esphome::optional'
   36 | template<typename T> class optional {  // NOLINT
      |                            ^~~~~~~~
In file included from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/node_handle.h:39,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/bits/hashtable.h:37,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/unordered_map:46,
                 from /Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/functional:61,
                 from src/esphome/core/component.h:4,
                 from src/esphome/components/binary_sensor/automation.h:5,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/Users/climax/.platformio/packages/toolchain-xtensa/xtensa-lx106-elf/include/c++/10.3.0/optional:60:11: note:                 'template<class _Tp> class std::optional'
   60 |     class optional;
      |           ^~~~~~~~
esp-smartmeter-test2.yaml:88:61: error: expected '{' before '<' token
esp-smartmeter-test2.yaml:88:62: error: expected primary-expression before 'float'
*** [.pioenvs/smartmeter/src/main.cpp.o] Error 1
========================================= [FAILED] Took 4.28 seconds =========================================`
```
here is my config.yaml

```
external_components:
  - source: github://jplitza/esphome_components
#external_components:
  #- source:
  #    type: local
  #    path: my_components
  #    #components: [ obis ]
  #- source: github://oromis911/Logarex-LK13B
  #  components: [ obis ]
substitutions:
  lower_devicename: "wemosd1mini"
  device_name: "smartmeter"
  config_version: "v2022.10.29"

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".climax"

  ap:
    ssid: "{device_name}"
    password: "12345678"

logger:
  baud_rate: 0

ota:
  password: "pass"
  port: 8266
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: ${device_name}
  topic_prefix: ${lower_devicename}/${device_name}
  discovery: false

web_server:
  port: 80
  #local: true

uart:
    id: uart_bus
    rx_pin: GPIO3
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1

obis:
  id: obis0
  uart_id: uart_bus

globals:
  - id: total_pulses
    type: int
    restore_value: false
    initial_value: '706615'  # hier kann der Gaszählerstand initialisiert werden

binary_sensor:
  - platform: gpio
    id: internal_pulse_counter
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
    name: "Live-Impuls"
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - lambda: id(total_pulses) += 1;

sensor:
  - platform: template
    name: "Gasverbrauch"
    device_class: gas
    unit_of_measurement: "m³"
    state_class: "total_increasing"
    accuracy_decimals: 2
    lambda: |-
      return id(total_pulses) * 0.01;
  - platform: template
    name: "Gaswert Raw"
    #update_interval: 2s
    device_class: gas
    unit_of_measurement: ""
    state_class: "total_increasing"
    accuracy_decimals: 0
    lambda: |-
      return id(total_pulses);
  - platform: obis
    obis_id: obis0
    channel: "1-0:1.8.0*255"
    name: "Bezug"
    unit_of_measurement: "kWh"
    accuracy_decimals: 7
#  - platform: obis
#    channel: "1-0:16.7.0*255"
#    name: "Wirkleistung"
#    unit_of_measurement: "W"
#    accuracy_decimals: 2
#  - platform: obis
#    channel: "1-0:2.8.0*255"
#    name: "Einspeisung"
#    unit_of_measurement: "kWh"
#    accuracy_decimals: 7
#  - platform: obis
#    channel: "1-0:14.7.0*255"
#    name: "Frequenz"
#    unit_of_measurement: "Hz"
#    accuracy_decimals: 2
#  - platform: obis
#    channel: "1-0:32.7.0*255"
#    name: "U-L1"
#    unit_of_measurement: "V"
#    accuracy_decimals: 2
#  - platform: obis
#    channel: "1-0:52.7.0*255"
#    name: "U-L2"
#    unit_of_measurement: "V"
#    accuracy_decimals: 2
#  - platform: obis
#    channel: "1-0:72.7.0*255"
#    name: "U-L3"
#    unit_of_measurement: "V"
#    accuracy_decimals: 2
#  - platform: obis
#    channel: "1-0:31.7.0*255"
#    name: "I-L1"
#    unit_of_measurement: "A"
#    accuracy_decimals: 2
#  - platform: obis
#    channel: "1-0:51.7.0*255"
#    name: "I-L2"
#    unit_of_measurement: "A"
#    accuracy_decimals: 2
#  - platform: obis
#    channel: "1-0:71.7.0*255"
#    name: "I-L3"
#    unit_of_measurement: "A"
#    accuracy_decimals: 2

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
  - platform: template
    name: "Config Version"
    lambda: |-
      return {"$config_version"};

switch:
  - platform: restart
    name: "Restart"
```
